### PR TITLE
Fix broken link in confirm email

### PR DESCRIPTION
**Pull request by rbren**

### CODE REVIEW

**Comment by fjorgemota** [comment]
Could you merge this PR, @aarondl? It seems to be as important as the fix for the recover_html.tpl merged sometime ago.

**Comment by aarondl** [comment]
Hadn't noticed this. Sorry. Thanks for the PR @rbren

**Comment by fjorgemota** [comment]
Just as a FYI apparently the bindata.go needs to be regenerated as well so this PR and the PR #5 is applied to everyone using this package, @aarondl. =)

**Comment by aarondl** [comment]
I hate bindata so much :) Will do it in a moment.

**Pull request merged**
